#!/usr/bin/env python

import argparse

import leo_fw
from leo_fw.test_hw import TestHW

parser = argparse.ArgumentParser(description="Test Leo Core controller")

parser.add_argument(
    "-r",
    "--record",
    dest="rosbag",
    action="store_false",
    help="record bug file",
)
parser.add_argument(
    "-hw",
    dest="hardware",
    type=TestHW,
    choices=list(TestHW),
    default="all",
    help="hardware to test",
)

args = parser.parse_args()

leo_fw.test_hw(
    rosbag=args.rosbag,
    hardware=args.hardware,
)

